name: Event Filters and Activity Types
 
on: 
 pull_request:
   types: 
    - opened
    - synchronize
    - closed
   branches:
     - main
jobs: 
 echo_Filter:
   runs-on: ubuntu-latest
   steps: 
     - run: echo " Running whenever a PR is opened or synchronized  or Closed AND base branch is master."
