name: Workflow expression
on:
 push:
 workflow_dispatch:
  inputs:
   debug: 
    type: boolean
    default: false
jobs:
 echo:
  runs-on: ubuntu-latest
  steps:
   - name: '[debug] Print startup info'
     if: ${{inputs.debug}}
     run: |
      echo "Triggered by: ${{github.event_name}}"
      echo "Branch is: ${{github.ref}}"
   - name: '[debug] Print when triggered from master'
     if: ${{ inputs.debug && github.ref == 'refs/heads/main' }}
     run: |
      echo "I was triggered from main"
